const express = require("express");
const fs = require("fs");
const path = require("path");

const app = express();
app.use(express.json());

const DATA_FILE = path.join(__dirname, "todos.json");//It creates an absolute, safe file path pointing to todos.json in the same folder as your code.

// --------------------
// Helper functions
// --------------------
function readTodos() {
  if (!fs.existsSync(DATA_FILE)) {
    fs.writeFileSync(DATA_FILE, JSON.stringify([])); // if data file is not present then it create a 
  }                                                   // todos.json file.
  const data = fs.readFileSync(DATA_FILE, "utf-8");// if todos.json file exist then it send the data .
  return JSON.parse(data);
}

function writeTodos(todos) {
  fs.writeFileSync(DATA_FILE, JSON.stringify(todos, null, 2));
}

// --------------------
// GET /todos
// --------------------
app.get("/todos", (req, res) => {
  const todos = readTodos();
  res.status(200).json(todos);
});

// --------------------
// GET /todos/:id
// --------------------
app.get("/todos/:id", (req, res) => {
  const id = Number(req.params.id);
  const todos = readTodos();

  const todo = todos.find(t => t.id === id);
  if (!todo) {
    return res.status(404).send("Todo not found");
  }

  res.status(200).json(todo);
});

// --------------------
// POST /todos
// --------------------
app.post("/todos", (req, res) => {
  const { title, description } = req.body;

  if (!title || !description) {
    return res.status(400).send("Title and description required");
  }

  const todos = readTodos();

  const newTodo = {
    id: Date.now(),        // unique autogenerated id
    title,
    description
  };

  todos.push(newTodo);
  writeTodos(todos);

  res.status(201).json({ id: newTodo.id });
});

// --------------------
// PUT /todos/:id
// --------------------
app.put("/todos/:id", (req, res) => {
  const id = Number(req.params.id);
  const todos = readTodos();

  const index = todos.findIndex(t => t.id === id);
  if (index === -1) {
    return res.status(404).send("Todo not found");
  }

  todos[index] = {
    ...todos[index],
    ...req.body
  };

  writeTodos(todos);
  res.status(200).json(todos[index]);
});

// --------------------
// DELETE /todos/:id
// --------------------
app.delete("/todos/:id", (req, res) => {
  const id = Number(req.params.id);
  const todos = readTodos();

  const index = todos.findIndex(t => t.id === id);
  if (index === -1) {
    return res.status(404).send("Todo not found");
  }

  todos.splice(index, 1);
  writeTodos(todos);

  res.status(200).send("Todo deleted");
});

// --------------------
// 404 for all other routes
// --------------------
app.use((req, res) => {
  res.status(404).send("Not Found");
});

module.exports = app;
